//category
export const GET_ALL_CTEGORY = "GET_ALL_CTEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";

//brands
export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const GET_ONE_BRAND = "GET_ONE_BRAND";

//subcategory
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

//products
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

//auth
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN = "LOGIN";
export const LOGGED_USER = "LOGGED_USER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const RESETE_CODE = "RESETE_CODE";
export const RESETE_PASSWORD = "RESETE_PASSWORD";

//review
export const CREATE_REVIEW = "CREATE_REVIEW";
export const GIT_ALL_REVIEW_PRODUCT = "GIT_ALL_REVIEW_PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";

//wish-list
export const ADD_PRODUCT_TO_WISHLIST = "ADD_PRODUCT_TO_WISHLIST";
export const REMOVE_PRODUCT_FROM_WISHLIST = "REMOVE_PRODUCT_FROM_WISHLIST";
export const GIT_ALL_PRODUCTS_WISHLIST = "GIT_ALL_PRODUCTS_WISHLIST";

//error
export const GET_ERROR = "GET_ERROR";